// Placeholder chat seeds and fallback replies, one set per page.
// Real conversations will be generated by the backend grounded on the
// ExplanationPack — see packages/contracts/module/chat.py.

import type { ChatMessage } from '@/lib/types/chat'

export const PLACEHOLDER_SOLUTION_ID = 'sol-2026-W21-7d'

export const chatSeedPlan: ChatMessage[] = [
  {
    role: 'assistant',
    content:
      "Hi — I built this week's plan as a shortest-path problem across L14, L17 and L19. L19 is the bottleneck at 47.2 h: it's the only line that can run 2/5 format, so it absorbs every 44 cl SKU. One low-margin SKU dropped under tight capacity. Ask me about any slot or transition.",
  },
]

export const chatSeedCompare: ChatMessage[] = [
  {
    role: 'assistant',
    content:
      "I'm comparing the LineWise proposal against what actually ran (S_real). Headline: 7.2 h fewer changeovers, +4.1 pp OEE. Biggest single win was avoiding the Free Damm → Damm Lemon flip on L17 mid-week — 1.8 h in reality, 0.3 h in our plan. Ask me about any transition that changed.",
  },
]

export const chatSeedWhatIf: ChatMessage[] = [
  {
    role: 'assistant',
    content:
      "Inject a perturbation — urgent demand, a breakdown, or a maintenance shift — and I'll narrate the replan. Until then: L17 has the most slack right now (4.2 h headroom on Thursday), so urgent 1/3 demand routes there cheapest.",
  },
]

const FALLBACK_REPLIES: Record<string, string[]> = {
  plan: [
    "I'd ground that in the explanation pack, but the chat API isn't wired up yet — once the backend exposes /api/chat I'll answer from the structured facts.",
    "Good question. In the placeholder build I can only echo seeded turns; the live answer would cite the slot's rationale tags and SHAP-style drivers from the pack.",
    "Once the optimiser is producing an ExplanationPack I'll point at the exact transition that drives this. Right now I'm running on fixtures.",
  ],
  compare: [
    "Once the backend is live I'll diff S_opt vs S_real per-line and quote the specific transitions that differ. For now I only have the seeded narrative.",
    "Placeholder reply — the real chat will surface every transition where vs_baseline = 'avoided_in_opt' and explain the saving.",
  ],
  'what-if': [
    "When the replan endpoint exists I'll narrate what changed after your perturbation: dropouts, reroutes, new bottleneck. Right now I can't process the form on my own.",
    "Once you submit a perturbation the backend will build a fresh pack and I'll diff it against the original. Currently this input is a stub.",
  ],
  insights: [
    "Insights placeholder — wired up in a later phase.",
  ],
}

export function pickFallback(view?: string): string {
  const pool = FALLBACK_REPLIES[view ?? 'plan'] ?? FALLBACK_REPLIES.plan
  return pool[Math.floor(Math.random() * pool.length)]
}
