"""Compare graph/v1 partitioner vs implementacion_v2 on all weekly windows.

This script reuses the v2 makespan dataset generated by ``report_v2.py`` and
runs the original graph partitioner from ``services/optimizer/graph`` against
the same planning graphs.

Run from repo root:

    python -m services.optimizer.app.report_v1_v2

Outputs:

* ``services/optimizer/reports/optimizer_v1_v2_comparison.csv``
* ``services/optimizer/reports/optimizer_v1_v2_comparison.md``
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from time import perf_counter
from typing import Any

import networkx as nx
import pandas as pd

from services.node_cost_ml.app.inference import load_artefacts
from services.optimizer.app.graph_builder import (
    DATA_DIR,
    LINE_IDS,
    REPORTS_DIR,
    build_historical_wo_graph,
    build_planning_graph,
)
from services.optimizer.app.report_v2 import (
    _historical_line_totals,
    _load_clean_data,
    _to_markdown,
    _window_work_orders,
)

REPO_ROOT = Path(__file__).resolve().parents[3]
GRAPH_DIR = REPO_ROOT / "services" / "optimizer" / "graph"
if str(GRAPH_DIR) not in sys.path:
    sys.path.insert(0, str(GRAPH_DIR))

from line_partitioner import partition_from_graph, verify_partition  # noqa: E402


@dataclass(frozen=True)
class V1Config:
    time_budget_s: float = 4.0
    move_strategy: str = "first_improvement"
    delta_balance_h: float = 0.5
    eps: float = 1e-3
    max_iterations: int = 500
    max_no_improve: int = 20


def generate_v1_v2_report(
    *,
    data_dir: Path = DATA_DIR,
    reports_dir: Path = REPORTS_DIR,
    v2_csv: Path | None = None,
    config: V1Config = V1Config(),
    limit: int | None = None,
) -> tuple[Path, Path]:
    reports_dir.mkdir(parents=True, exist_ok=True)
    clean = _load_clean_data(data_dir)
    ml_model = load_artefacts()

    v2_path = v2_csv or reports_dir / "optimizer_v2_makespan_comparison.csv"
    if not v2_path.exists():
        raise FileNotFoundError(
            f"Missing v2 comparison CSV: {v2_path}. Run python -m services.optimizer.app.report_v2 first."
        )
    v2 = pd.read_csv(v2_path)
    windows = tuple(clean["demand"]["window_id"].drop_duplicates())
    if limit is not None:
        windows = windows[:limit]

    rows: list[dict[str, Any]] = []
    started = perf_counter()
    for index, window_id in enumerate(windows, start=1):
        t0 = perf_counter()
        graph = build_planning_graph(
            window_id,
            demand_df=clean["demand"],
            capability_df=clean["capability"],
            changeover_df=clean["changeovers"],
            ml_model=ml_model,
        )
        v1 = partition_from_graph(
            graph,
            time_budget_s=config.time_budget_s,
            move_strategy=config.move_strategy,
            delta_balance_h=config.delta_balance_h,
            eps=config.eps,
            max_iterations=config.max_iterations,
            max_no_improve=config.max_no_improve,
        )
        verification = _verify_v1(graph, v1)
        real_graphs = build_historical_wo_graph(
            window_id,
            demand_df=clean["demand"],
            wo_df=clean["wo"],
            wo_co_df=clean["wo_changeovers"],
            ml_model=ml_model,
        )
        window_wo = _window_work_orders(clean["wo"], clean["demand"], window_id)
        real_by_line = {
            line: _historical_line_totals(real_graphs.get(line, nx.DiGraph()), window_wo, line)
            for line in LINE_IDS
        }
        v2_row = v2[v2["window_id"] == window_id]
        if v2_row.empty:
            raise KeyError(f"window {window_id!r} missing from {v2_path}")
        row = _comparison_row(
            window_id=window_id,
            graph=graph,
            v1=v1,
            v1_verify_ok=verification.ok,
            real_by_line=real_by_line,
            v2_row=v2_row.iloc[0],
            elapsed_s=perf_counter() - t0,
        )
        rows.append(row)
        print(
            f"[{index}/{len(windows)}] {window_id}: "
            f"v1_sim={row['v1_optimal_simulated_makespan_hours']:.2f}h "
            f"v2_sim={row['v2_optimal_simulated_makespan_hours']:.2f}h "
            f"delta(v1-v2)={row['optimal_simulated_delta_v1_minus_v2_hours']:+.2f}h "
            f"elapsed={row['v1_elapsed_seconds']:.1f}s"
        )

    df = pd.DataFrame(rows)
    csv_path = reports_dir / "optimizer_v1_v2_comparison.csv"
    md_path = reports_dir / "optimizer_v1_v2_comparison.md"
    df.to_csv(csv_path, index=False)
    md_path.write_text(
        _render_report(
            df,
            config=config,
            generated_at=datetime.now().isoformat(timespec="seconds"),
            elapsed_s=perf_counter() - started,
        ),
        encoding="utf-8",
    )
    return csv_path, md_path


def _verify_v1(graph: nx.MultiDiGraph, result: Any) -> Any:
    def can_produce(sku: str, line: int) -> bool:
        return line in graph.nodes[sku].get("line_data", {})

    def node_cost(sku: str, line: int) -> float:
        return float(graph.nodes[sku]["line_data"][line]["predicted_hours"])

    def edge_cost(a: str, b: str, line: int) -> float:
        if a == b:
            return 0.0
        data = graph.get_edge_data(a, b, key=line)
        return float(data.get("hours", 8.0)) if data is not None else 8.0

    return verify_partition(result, list(graph.nodes), can_produce, edge_cost, node_cost)


def _comparison_row(
    *,
    window_id: str,
    graph: nx.MultiDiGraph,
    v1: Any,
    v1_verify_ok: bool,
    real_by_line: dict[int, dict[str, float]],
    v2_row: pd.Series,
    elapsed_s: float,
) -> dict[str, Any]:
    v1_sim = _simulated_optimizer_makespan(v1.makespan_per_line_hours, real_by_line)
    v1_sim_maint = _simulated_optimizer_makespan(
        v1.makespan_per_line_hours,
        real_by_line,
        include_maintenance=True,
    )

    row: dict[str, Any] = {
        "window_id": window_id,
        "node_count": graph.number_of_nodes(),
        "v1_valid": bool(v1_verify_ok and v1.feasible),
        "v2_valid": bool(v2_row["valid_solution"]),
        "v1_makespan_hours": float(v1.makespan_hours),
        "v2_makespan_hours": float(v2_row["v2_makespan_hours"]),
        "raw_delta_v1_minus_v2_hours": (
            float(v1.makespan_hours) - float(v2_row["v2_makespan_hours"])
        ),
        "v1_optimal_simulated_makespan_hours": v1_sim,
        "v2_optimal_simulated_makespan_hours": float(
            v2_row["v2_makespan_plus_cleaning_plus_real_inefficiencies_hours"]
        ),
        "optimal_simulated_delta_v1_minus_v2_hours": (
            v1_sim
            - float(v2_row["v2_makespan_plus_cleaning_plus_real_inefficiencies_hours"])
        ),
        "v1_optimal_simulated_with_maintenance_hours": v1_sim_maint,
        "v2_optimal_simulated_with_maintenance_hours": float(
            v2_row[
                "v2_makespan_plus_cleaning_maintenance_plus_real_inefficiencies_hours"
            ]
        ),
        "optimal_simulated_with_maintenance_delta_v1_minus_v2_hours": (
            v1_sim_maint
            - float(
                v2_row[
                    "v2_makespan_plus_cleaning_maintenance_plus_real_inefficiencies_hours"
                ]
            )
        ),
        "v1_total_hours": float(v1.total_hours),
        "v1_iterations": int(v1.iterations),
        "v1_elapsed_seconds": float(v1.elapsed_s),
        "window_elapsed_seconds": float(elapsed_s),
    }

    for line in LINE_IDS:
        row[f"v1_load_l{line}_hours"] = float(v1.makespan_per_line_hours.get(line, 0.0))
        row[f"v2_load_l{line}_hours"] = float(v2_row[f"v2_plus_cleaning_ineff_l{line}_hours"]) - (
            real_by_line[line]["production_inefficiency_hours"]
            + real_by_line[line]["cleaning_wo_hours"]
        )
        row[f"v1_n_l{line}"] = len(v1.sequences.get(line, ()))
        row[f"real_ineff_l{line}_hours"] = real_by_line[line]["production_inefficiency_hours"]
        row[f"real_cleaning_l{line}_hours"] = real_by_line[line]["cleaning_wo_hours"]

    return row


def _simulated_optimizer_makespan(
    loads_by_line: dict[int, float],
    real_by_line: dict[int, dict[str, float]],
    *,
    include_maintenance: bool = False,
) -> float:
    values = []
    for line in LINE_IDS:
        burden = (
            real_by_line[line]["production_inefficiency_hours"]
            + real_by_line[line]["cleaning_wo_hours"]
        )
        if include_maintenance:
            burden += real_by_line[line]["maintenance_rerun_hours"]
        values.append(float(loads_by_line.get(line, 0.0)) + burden)
    return max(values)


def _render_report(
    df: pd.DataFrame,
    *,
    config: V1Config,
    generated_at: str,
    elapsed_s: float,
) -> str:
    raw_delta = df["raw_delta_v1_minus_v2_hours"]
    sim_delta = df["optimal_simulated_delta_v1_minus_v2_hours"]
    sim_maint_delta = df["optimal_simulated_with_maintenance_delta_v1_minus_v2_hours"]

    wins_v1_raw = int((raw_delta < 0).sum())
    wins_v2_raw = int((raw_delta > 0).sum())
    ties_raw = len(df) - wins_v1_raw - wins_v2_raw
    wins_v1_sim = int((sim_delta < 0).sum())
    wins_v2_sim = int((sim_delta > 0).sum())
    ties_sim = len(df) - wins_v1_sim - wins_v2_sim

    summary = pd.DataFrame([
        {
            "metric": "raw makespan",
            "v1_mean_h": df["v1_makespan_hours"].mean(),
            "v2_mean_h": df["v2_makespan_hours"].mean(),
            "v1_minus_v2_h": raw_delta.mean(),
        },
        {
            "metric": "optimal simulated",
            "v1_mean_h": df["v1_optimal_simulated_makespan_hours"].mean(),
            "v2_mean_h": df["v2_optimal_simulated_makespan_hours"].mean(),
            "v1_minus_v2_h": sim_delta.mean(),
        },
        {
            "metric": "optimal simulated + maintenance",
            "v1_mean_h": df["v1_optimal_simulated_with_maintenance_hours"].mean(),
            "v2_mean_h": df["v2_optimal_simulated_with_maintenance_hours"].mean(),
            "v1_minus_v2_h": sim_maint_delta.mean(),
        },
    ])

    best_v1 = df.sort_values("optimal_simulated_delta_v1_minus_v2_hours").head(8)
    best_v2 = df.sort_values("optimal_simulated_delta_v1_minus_v2_hours", ascending=False).head(8)

    return "\n".join([
        "# Optimizer v1 vs v2 Comparison",
        "",
        f"Generated at: `{generated_at}`",
        "",
        "## Configuration",
        "",
        f"- v1 source: `services/optimizer/graph/line_partitioner.py`",
        f"- v2 source: `services/optimizer/app/implementacion_v2.py` via existing `optimizer_v2_makespan_comparison.csv`",
        f"- v1 `time_budget_s`: {config.time_budget_s}",
        f"- v1 `move_strategy`: {config.move_strategy}",
        f"- v1 `delta_balance_h`: {config.delta_balance_h}",
        f"- v1 `max_no_improve`: {config.max_no_improve}",
        f"- Runtime: {elapsed_s:.1f} s",
        "",
        "## Mean Results",
        "",
        _to_markdown(summary, floatfmt=".2f"),
        "",
        "Positive `v1_minus_v2_h` means v1 is slower; negative means v1 is better.",
        "",
        "## Win Counts",
        "",
        f"- Raw makespan: v1 wins {wins_v1_raw}/{len(df)}, v2 wins {wins_v2_raw}/{len(df)}, ties {ties_raw}.",
        f"- Optimal simulated: v1 wins {wins_v1_sim}/{len(df)}, v2 wins {wins_v2_sim}/{len(df)}, ties {ties_sim}.",
        f"- Valid v1 windows: {int(df['v1_valid'].sum())}/{len(df)}",
        f"- Valid v2 windows: {int(df['v2_valid'].sum())}/{len(df)}",
        "",
        "## Best v1 Advantages",
        "",
        _to_markdown(
            best_v1[[
                "window_id",
                "v1_optimal_simulated_makespan_hours",
                "v2_optimal_simulated_makespan_hours",
                "optimal_simulated_delta_v1_minus_v2_hours",
            ]],
            floatfmt=".2f",
        ),
        "",
        "## Best v2 Advantages",
        "",
        _to_markdown(
            best_v2[[
                "window_id",
                "v1_optimal_simulated_makespan_hours",
                "v2_optimal_simulated_makespan_hours",
                "optimal_simulated_delta_v1_minus_v2_hours",
            ]],
            floatfmt=".2f",
        ),
        "",
    ]) + "\n"


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Compare optimizer v1 and v2")
    parser.add_argument("--budget", type=float, default=V1Config.time_budget_s)
    parser.add_argument(
        "--strategy",
        choices=["first_improvement", "best_improvement"],
        default=V1Config.move_strategy,
    )
    parser.add_argument("--delta", type=float, default=V1Config.delta_balance_h)
    parser.add_argument("--max-no-improve", type=int, default=V1Config.max_no_improve)
    parser.add_argument("--limit", type=int, default=None)
    return parser.parse_args()


def main() -> None:
    args = _parse_args()
    config = V1Config(
        time_budget_s=args.budget,
        move_strategy=args.strategy,
        delta_balance_h=args.delta,
        max_no_improve=args.max_no_improve,
    )
    csv_path, md_path = generate_v1_v2_report(config=config, limit=args.limit)
    print(f"CSV: {csv_path}")
    print(f"Markdown: {md_path}")


if __name__ == "__main__":
    main()

