"""Conversational explainability — LLM-powered chat grounded on an ExplanationPack.

The chat is **fully LLM-powered** and runs on the backend: every assistant
turn, including the very first message that greets the user and narrates the
solution, is generated by an LLM call inside the :class:`ChatContract`
implementation. The backend does not template prose — it only ships
structured facts (see ``explainability.py``) and orchestrates the LLM call.

Per-turn flow:

1. Frontend sends ``ChatRequest`` (history + new user turn + current view scope).
2. Backend loads the :class:`ExplanationPack` for the referenced ``solution_id``.
3. Backend slices the pack by ``ChatScope`` so the LLM context stays small.
4. Backend prompts the LLM with that sliced pack + history; the system prompt
   enforces grounding — "only claim facts that appear in the pack; otherwise
   say you don't know".
5. Backend returns ``ChatResponse`` to the frontend.

The frontend decides its own suggested-question UX; the contract intentionally
does not generate suggestions.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal, Protocol

from .explainability import ExplanationPack, GroundingKind
from .schemas import LineId

# ---------------------------------------------------------------------------
# Type aliases
# ---------------------------------------------------------------------------

ChatRole = Literal["user", "assistant", "system"]

ChatView = Literal["plan", "compare", "what-if", "insights"]


# ---------------------------------------------------------------------------
# Message + scope
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class ChatMessage:
    """One turn of the conversation. Plain text — the chat is grounded on the
    pack but the wire format is just role + content."""

    role: ChatRole
    content: str


@dataclass(frozen=True)
class ChatScope:
    """What the user is currently looking at in the UI.

    All fields are optional. Set the ones that apply; the chat implementation
    uses them to focus the LLM's grounding on the relevant slice of the
    :class:`ExplanationPack` instead of dumping the whole pack into context.

    Example — planner clicked a Wednesday changeover on L14::

        ChatScope(view="plan", line_id=14, transition_id="14:slot_023->slot_024")
    """

    view: ChatView | None = None
    line_id: LineId | None = None
    slot_id: str | None = None
    transition_id: str | None = None
    sku_id: str | None = None
    dropped_sku_id: str | None = None


# ---------------------------------------------------------------------------
# Request / response
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class ChatRequest:
    """One turn from the frontend. ``user_message`` is the just-typed input.

    For the very first turn (the welcome / solution narration), the frontend
    sends an empty ``history`` and a seed ``user_message`` such as
    ``"<<intro>>"`` agreed in the implementation. The backend treats any
    non-empty user_message as real input.
    """

    solution_id: str                             # which ExplanationPack to ground on
    scope: ChatScope
    history: tuple[ChatMessage, ...]             # oldest first; excludes ``user_message``
    user_message: str


@dataclass(frozen=True)
class GroundingReference:
    """A pointer to a fact in the :class:`ExplanationPack` that the assistant
    used when forming its reply.

    The UI can use these to highlight the slot / transition / theme the answer
    is about — e.g. flash the Gantt edge that backs a sentence.
    """

    kind: GroundingKind
    ref_id: str                                  # e.g. slot_id, transition_id, theme_id


@dataclass(frozen=True)
class ChatResponse:
    """One assistant turn. ``referenced`` is best-effort and may be empty if
    the implementation does not extract groundings from the LLM output."""

    assistant_message: str
    referenced: tuple[GroundingReference, ...] = field(default_factory=tuple)


# ---------------------------------------------------------------------------
# Contract
# ---------------------------------------------------------------------------

class ChatContract(Protocol):
    """LLM-powered grounded chat over an :class:`ExplanationPack`.

    Implementations are responsible for:

    * Loading the pack (by ``solution_id``) — either passed in directly via
      the ``pack`` argument or fetched from a store the implementation owns.
    * Slicing the pack by ``ChatScope`` so the LLM context stays small.
    * Calling the LLM with a system prompt that enforces grounding ("only
      claim facts that appear in the pack; otherwise say you don't know").
    * Optionally extracting :class:`GroundingReference` items from the
      assistant's reply for the UI to highlight.

    Latency target for the demo: < 2 s per turn on the planning week. The
    method is async to allow a streaming transport (SSE) in a later
    iteration; the initial version returns the full reply at once.
    """

    async def chat(
        self,
        request: ChatRequest,
        pack: ExplanationPack,
    ) -> ChatResponse:
        ...
